apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-pod
  namespace: default
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels: 
        app: pong 
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60 
      containers:
      - name: pong-api
        image: jnkroeker/pong-image:0.0.4
        imagePullPolicy: IfNotPresent 
        ports:
        - name: pong-api
          containerPort: 4000
      - name: outliers-api
        image: jnkroeker/outliers-image:0.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: outliers-api
          containerPort: 50051
---
apiVersion: v1 
kind: Service 
metadata:   
  name: pong-service 
  namespace: default 
spec: 
  type: ClusterIP
  selector:
    app: pong 
  ports:
  - name: pong-api 
    port: 4000 
    targetPort: pong-api 