FROM python 

RUN mkdir /service 
COPY py/ /service/outliers
COPY protobufs/ /service/protobufs 

WORKDIR /service/outliers
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt 
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/outliers.proto

EXPOSE 50051 
ENTRYPOINT [ "python", "outliers.py"]