// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: protobufs/outliers.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Metric) Reset() {
	*x = Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_outliers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_outliers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_protobufs_outliers_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OutliersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *OutliersRequest) Reset() {
	*x = OutliersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_outliers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutliersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutliersRequest) ProtoMessage() {}

func (x *OutliersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_outliers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutliersRequest.ProtoReflect.Descriptor instead.
func (*OutliersRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_outliers_proto_rawDescGZIP(), []int{1}
}

func (x *OutliersRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type OutliersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indicies []int32 `protobuf:"varint,1,rep,packed,name=indicies,proto3" json:"indicies,omitempty"`
}

func (x *OutliersResponse) Reset() {
	*x = OutliersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_outliers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutliersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutliersResponse) ProtoMessage() {}

func (x *OutliersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_outliers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutliersResponse.ProtoReflect.Descriptor instead.
func (*OutliersResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_outliers_proto_rawDescGZIP(), []int{2}
}

func (x *OutliersResponse) GetIndicies() []int32 {
	if x != nil {
		return x.Indicies
	}
	return nil
}

var File_protobufs_outliers_proto protoreflect.FileDescriptor

var file_protobufs_outliers_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x6c,
	0x69, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x06, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34,
	0x0a, 0x0f, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x22, 0x2e, 0x0a, 0x10, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x32, 0x39, 0x0a, 0x08, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x65, 0x72, 0x73,
	0x12, 0x2d, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x10, 0x2e, 0x4f, 0x75, 0x74,
	0x6c, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4f,
	0x75, 0x74, 0x6c, 0x69, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x17, 0x5a, 0x15, 0x70, 0x68, 0x61, 0x6c, 0x63, 0x6f, 0x6e, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_outliers_proto_rawDescOnce sync.Once
	file_protobufs_outliers_proto_rawDescData = file_protobufs_outliers_proto_rawDesc
)

func file_protobufs_outliers_proto_rawDescGZIP() []byte {
	file_protobufs_outliers_proto_rawDescOnce.Do(func() {
		file_protobufs_outliers_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_outliers_proto_rawDescData)
	})
	return file_protobufs_outliers_proto_rawDescData
}

var file_protobufs_outliers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobufs_outliers_proto_goTypes = []interface{}{
	(*Metric)(nil),           // 0: Metric
	(*OutliersRequest)(nil),  // 1: OutliersRequest
	(*OutliersResponse)(nil), // 2: OutliersResponse
}
var file_protobufs_outliers_proto_depIdxs = []int32{
	0, // 0: OutliersRequest.metrics:type_name -> Metric
	1, // 1: Outliers.Detect:input_type -> OutliersRequest
	2, // 2: Outliers.Detect:output_type -> OutliersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_outliers_proto_init() }
func file_protobufs_outliers_proto_init() {
	if File_protobufs_outliers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_outliers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_outliers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutliersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_outliers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutliersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_outliers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_outliers_proto_goTypes,
		DependencyIndexes: file_protobufs_outliers_proto_depIdxs,
		MessageInfos:      file_protobufs_outliers_proto_msgTypes,
	}.Build()
	File_protobufs_outliers_proto = out.File
	file_protobufs_outliers_proto_rawDesc = nil
	file_protobufs_outliers_proto_goTypes = nil
	file_protobufs_outliers_proto_depIdxs = nil
}
