# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outliers.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoutliers.proto\"%\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"+\n\x0fOutliersRequest\x12\x18\n\x07metrics\x18\x01 \x03(\x0b\x32\x07.Metric\"$\n\x10OutliersResponse\x12\x10\n\x08indicies\x18\x01 \x03(\x05\x32\x39\n\x08Outliers\x12-\n\x06\x44\x65tect\x12\x10.OutliersRequest\x1a\x11.OutliersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'outliers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METRIC']._serialized_start=18
  _globals['_METRIC']._serialized_end=55
  _globals['_OUTLIERSREQUEST']._serialized_start=57
  _globals['_OUTLIERSREQUEST']._serialized_end=100
  _globals['_OUTLIERSRESPONSE']._serialized_start=102
  _globals['_OUTLIERSRESPONSE']._serialized_end=138
  _globals['_OUTLIERS']._serialized_start=140
  _globals['_OUTLIERS']._serialized_end=197
# @@protoc_insertion_point(module_scope)
